import { Inter } from 'next/font/google';

import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';

import { auth } from '@/auth';

import type { Children } from '@/types';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<Children>) {
    const session = await auth();

    return (
        <SessionProvider session={session}>
            <html lang="en">
                <body
                    className={inter.className}
                    suppressHydrationWarning
                >
                    {children}
                </body>
            </html>
        </SessionProvider>
    );
}
